-- AlterTable
ALTER TABLE "User" ADD COLUMN "aiTokensUsedDaily" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiTokensUsedMonthly" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiTokensDailyResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "aiTokensMonthlyResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
